version: "3"

volumes:
  peer0.insurance.pca.com:

networks:
  pcanet:

services:
  peer0.insurance.pca.com:
    networks:
      - pcanet
    container_name: peer0.insurance.pca.com
    image: hyperledger/fabric-peer:latest
    volumes:
      - ../crypto-material/peerOrganizations/insurance.pca.com/peers/peer0.insurance.pca.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-material/peerOrganizations/insurance.pca.com/peers/peer0.insurance.pca.com/tls:/etc/hyperledger/fabric/tls
      - peer0.insurance.pca.com:/var/hyperledger/production
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt 
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key 
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt 
      - CORE_PEER_ID=peer0.insurance.pca.com
      - CORE_PEER_ADDRESS=peer0.insurance.pca.com:7054
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7054
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.pca.com:7054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.pca.com:7054
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7054:7054